---
- name: Ansible Playbook to Test Unix Based managed nodes connectivity using ping module
  hosts: all
  ignore_errors: yes
  ignore_unreachable: yes
  gather_facts: no
 
  tasks:
    - name: Test connectivity using ping module
      ping:  
      register: ping_result

    - debug:
        var: ping_result

    - name: Printing if Node is rechable
      debug: 
        msg: "Congratulations!! You are able to reach your managed node"
      when: '"ping" in ping_result and ping_result.ping=="pong"'

    - name: Printing if Node is NOT rechable
      debug:
        msg: "Sorry !!, You are Unable to reach your managed node"
      when: '"unreachable" in ping_result and ping_result.unreachable'


